# Generated by Django 4.2.5 on 2024-01-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='password',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='password',
            field=models.TextField(blank=True, null=True),
        ),
    ]
