# Generated by Django 4.2.5 on 2024-01-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_driverprofile_password_riderprofile_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='status',
            field=models.CharField(blank=True, choices=[('available', 'Available'), ('busy', 'Busy')], max_length=128, null=True),
        ),
    ]
